### ISSUE TITLE
incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)

### ISSUE THREAD

**Issue by EvegniyK** [joeyates/imap-backup#101]
Hello

I saw this error message in the log. Maybe it is a bug.
Maybe this is duplicate #93 , but the error stack is different.

Traceback (most recent call last):
        18: from /usr/local/bin/imap-backup:23:in `<main>'
        17: from /usr/local/bin/imap-backup:23:in `load'
        16: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/bin/imap-backup:76:in `<top (required)>'
        15: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/list.rb:18:in `each_connection'
        14: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/list.rb:18:in `each'
        13: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/list.rb:20:in `block in each_connection'
        12: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:62:in `run_backup'
        11: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:125:in `each_folder'
        10: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:125:in `each'
         9: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:128:in `block in each_folder'
         8: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:68:in `block in run_backup'
         7: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/downloader.rb:15:in `run'
         6: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/downloader.rb:15:in `with_index'
         5: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/downloader.rb:15:in `each'
         4: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/downloader.rb:25:in `block in run'
         3: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/serializer/mbox.rb:43:in `save'
         2: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/serializer/mbox_store.rb:60:in `add'
         1: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/email/mboxrd/message.rb:26:in `to_serialized'
/var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/email/mboxrd/message.rb:26:in `+': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
        17: from /usr/local/bin/imap-backup:23:in `<main>'
        16: from /usr/local/bin/imap-backup:23:in `load'
        15: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/bin/imap-backup:76:in `<top (required)>'
        14: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/list.rb:18:in `each_connection'
        13: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/list.rb:18:in `each'
        12: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/list.rb:20:in `block in each_connection'
        11: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:62:in `run_backup'
        10: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:125:in `each_folder'
         9: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:125:in `each'
         8: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:128:in `block in each_folder'
         7: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:68:in `block in run_backup'
         6: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/downloader.rb:15:in `run'
         5: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/downloader.rb:15:in `with_index'
         4: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/downloader.rb:15:in `each'
         3: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/downloader.rb:25:in `block in run'
         2: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/serializer/mbox.rb:43:in `save'
         1: from /var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/serializer/mbox_store.rb:63:in `add'
/var/lib/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/serializer/mbox_store.rb:64:in `rescue in add': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)

**Comment by joeyates** [comment]
Hi @EvegniyK 

If you are still having this problem, please install a version >= 3.4.1 and activate debug mode.
You will see **all** data sent to and received from the IMAP server - that should help to understand the bytes thhat are causing the error.

N.B. The debug log will include passwords in the clear, so it'll need redacting before posting here!
