### ISSUE TITLE
Feature Request: Prevent deletion of messages in certain folders

### ISSUE THREAD

**Issue by badda71** [joeyates/imap-backup#102]
I have a feature request: My email provider deletes messages after a certain period of time. I would, however like to keep them in my backup. For this, I would like to prevent deletion of messages in certain email folders. These folders should be configurable in config.json.

**Comment by joeyates** [comment]
Hi @badda71 

I think that imap-backup already handles what you need... As it makes a "cumulative" backup, it never deletes messages from disk. So, when your email provider deletes a message, you will still find it in the backup.
