### ISSUE TITLE
Restore on another server possible?

### ISSUE THREAD

**Issue by robdejonge** [joeyates/imap-backup#105]
Because I'm having issues importing the mbox file generated by this tool into Apple Mail, due to it not understanding a properly formatted mbox it seems, I am wondering if I can create a backup with this tool, then change the server name and have it 'restore' the backup to the server?

**Comment by joeyates** [comment]
Hi @robdejonge 

Yes, you certainly can restore to a different server or service.

First, run `imap setup` and add authentication to the new service.

Next, if the email address you are restoring to is different from the one that was backed up, rename the directory containing the existing backup to match the email address for the new service.

Then run `imap restore -a NEW_SERVICE_EMAIL_ACCOUNT`

**Comment by robdejonge** [comment]
Thanks
