### ISSUE TITLE
How does this work with duplicate email under different labels?

### ISSUE THREAD

**Issue by slhck** [joeyates/imap-backup#110]
This is more of a question. I use Gmail, and most if not all my email is labeled. However, the special `[Gmail]/All Mail` folder will also contain all of those emails. At least when I browse it, I can see all labeled messages.

What will this tool download? Will it download each unique email, thus leading to essentially creating two copies of each email (the one in All Mail, and the one under its specific label)?

What is going to happen to messages with two or more labels?

Thanks for providing this utility!

**Comment by joeyates** [comment]
Hi @slhck 

imap-backup downloads in terms of IMAP *folders* and ignores *labels*.

Duplicate emails in different folders will get downloaded multiple times. I think the idea of folder blacklists (in #87) may be the best way to only back up what you need.

**Comment by slhck** [comment]
I see, thanks for clarifying! In that case there may be some duplicates (e.g., think a message labeled as `invoices` and `family`), but that's probably not a huge practical issue. So I'll close this for now.

There might be a possibility to de-dupe based on a database of Message-IDs: if a message has already been downloaded, it will simply be referenced by its ID. That however requires setting up an additional index for the downloaded data …

**Comment by semiligneous** [comment]
Appreciate this was somewhat asked and answered already, but does anyone have any practical solutions to this? Trying to decide which way to go - I suspect I will just accept the duplicates, but would be interested in opinions!

_Aside: did Google rename the special folders from `[Gmail]/All Mail` to [`Google Mail]/All Mail` at some point, or is it just my account?_

**Options:**

1) Let `imap-backup` behave the default way resulting in duplicates if a message is in one or more labels, plus Inbox plus All Mail.

Pros: Simple to set up, can find messages by label from the backup when needed
Cons: Longer to back up (approx 2x or more), more space on disk (approx 2x or more)


2) Exclude `[Google Mail]/All Mail` folder/label

Pros: Reduce duplicates and size/time by approx 50%, still retain ability to find message by label in the backup
Cons: If a message was archived and has no other label, it won't be backed up

3) Exclude every folder EXCEPT `[Google Mail]/All Mail` and `[Google Mail]/Sent`

Pros: Eliminate duplicates, and reduce time/space requirements to minimum
Cons: Lose ability to browse the backup by label

**Comment by slhck** [comment]
I think the simplest and most effective way would be to work with symlinks on-disk and a database that tracks message IDs (which should be the same) and their labels.

For example, an SQLite database could be used with a schema like this:

```sql
CREATE TABLE messages (
  id INTEGER PRIMARY KEY,
  message_id TEXT UNIQUE NOT NULL,
  download_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  file_path TEXT NOT NULL
);

CREATE TABLE labels (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE message_labels (
  message_id INTEGER,
  label_id INTEGER,
  FOREIGN KEY (message_id) REFERENCES messages(id),
  FOREIGN KEY (label_id) REFERENCES labels(id),
  PRIMARY KEY (message_id, label_id)
);
```

Then:

- Store unique messages in a flat structure only: `<backup_path>/messages/<message_id>.eml`
- Create a folder structure for labels: `<backup_path>/labels/<label_name>/`
- Use symlinks in label folders pointing to the actual message files

The changes needed would be a `sqlite3` dependency, then modifying the `serializer.rb` script to parse the message ID from the email content.

Possibly, sharding is needed to avoid a too large `messages` folder (too many files in one folder may not work), e.g. assigning `/messages/<shard>/<message_id>.eml`, where `<shard>` is the first two characters of the message ID's MD5 sum or similar.

The only problem is that this approach is not backwards-compatible, so a full download may be required.
