### ISSUE TITLE
Emails restored as unread

### ISSUE THREAD

**Issue by galmok** [joeyates/imap-backup#114]
I am testing imap-backup and when I mark an email as read, make an imap-backup, delete the email, and make an imap-restore, then email is restored, but is now marked as unread. 

Can the read/unread status also be backed up and restored somehow?

**Comment by joeyates** [comment]
Hi @galmok thanks for the question.

Currently, `imap-backup` does not save this info in the backup.
 
Theoretically, imap-backup could save message metadata (like the read/unread status) in its '.imap' files. It sounds like an interesting idea, but it would make backwards compatibility with older backups a bit complicated.

As always, PRs are welcome! :)

**Comment by galmok** [comment]
Too bad this isn't there yet. I feel this really needs to be there to make imap-backup truly useful. Regarding backwards compatibility, can't the imap file have this information as an optimal field with default values in the code or taken from the config file? It would make imap-backup more useful to make a seamless transition from one host to the next.

I don't know the imam protocol nor the language/libraries used, which makes me providing PRs for this project difficult.

**Comment by joeyates** [comment]
Hi @galmok 

I've just released version 7.0.1 which backs up and restores email flags.
