### ISSUE TITLE
Characters issue on Windows with path and passwords (incl. workaround)

### ISSUE THREAD

**Issue by graphcon** [joeyates/imap-backup#122]
### Description

If I want to modify backup path under Windows, I have to double backslashes.

### Steps to reproduce
1. In account menu, type 3 (modify backup path)
2. Copy and paste backup path from Explorer, e.g. d:\backup\imap-backup\xxx\
3. Hit enter
4. See path be like: dackupimap-backupxxxfolders
5. Type 3 again
6. Modify path to double backslashes: d:\\backup\\imap-backup\\xxx\\
7. Hit enter
8. See path be like: d:\backup\imap-backup\xxx\

### Workaround
Steps 5 through 8 are actually a workaround.

### AddOn
When I try to add a password, the same tool says passwords don't match when I copy/paste my password. I suppose it has issues with special characters in my password (like backslash, pipe, etc.).
Workaround to this: edit config.json ;)

**Comment by joeyates** [comment]
Hi @graphcon, thanks for opening the issue.

I've release version 6.0.0 with a fix for this.

The problem with '\' in paths should now be resolved, please try it out and let me know.

That said, I have been unable to replicate the problem with passwords. If you continue to see the problem, please open a specific issue, thanks!
