### ISSUE TITLE
How to select all folders?

### ISSUE THREAD

**Issue by MatejKovacic** [joeyates/imap-backup#125]
Hi, when I choose the account and then choose backup folders, there is a list of almost 400 folders (yes, I know). Is it possible to select them all?

**Comment by joeyates** [comment]
Hi @MatejKovacic 

Sorry for not getting back to you sooner.

The default behaviour of imap-backup is to backup all folders, so you don't need to do anything to get your desired result.

**Comment by joeyates** [comment]
Hello,

The default behaviour is to backup all folders, so you don't need to select
them all.
