### ISSUE TITLE
Question: Local messages not on remote

### ISSUE THREAD

**Issue by DocCyblade** [joeyates/imap-backup#127]
Nice little gem here, was wondering is there an option to purge local messages that are not on the remote but our on the local? Example, I remove delete 100 messages, still shows on local. Is there a purge local command

**Comment by joeyates** [comment]
Hi @DocCyblade 

What you're after is on the roadmap as the `imap-backup mirror` command.

The basic imap-backup functionality is greedy: it keeps all the messages it can, whether or not they are still available on the server.

The upcoming `imap-backup mirror` command will duplicate state between 2 IMAP servers or between a source server and disk. So it will prune messages as and when they disappear from the source server. (See also #114)

**Comment by joeyates** [comment]
@DocCyblade I've just releasse version 7.0.1 which includes the new 'mirror' command. Let me know if you have a chance to try it out!
