### ISSUE TITLE
Verbose? Status?

### ISSUE THREAD

**Issue by notflip** [joeyates/imap-backup#128]
So the command to actually start backing up, once everything is configured is `imap-backup backup`, I see that options can be added after the command but I can't seem to find what those options are?

**Is it possible to have output be shown in the console? Is there a verbose command?**

**Comment by joeyates** [comment]
Hi @notflip 

You can get verbose output by activating the logging option via `imap-backup setup`.

I've [added a note](https://github.com/joeyates/imap-backup/blob/main/docs/commands/setup.md#logging) in the docs.

**Comment by notflip** [comment]
Great! Thanks a lot for your work


Miguel Stevens

https://miguelstevens.be

0483 02 99 47






---- On Sun, 11 Sep 2022 13:12:52 +0200 Joe Yates ***@***.***> wrote ---





Hi https://github.com/notflip

You can get verbose output by activating the logging option via imap-backup setup.

I've https://github.com/joeyates/imap-backup/blob/main/docs/commands/setup.md#logging in the docs.
