### ISSUE TITLE
Error Restoring

### ISSUE THREAD

**Issue by metanodotto** [joeyates/imap-backup#129]
I've backed up my email address "my@email.com" on the old imap server and I'd like to restore it to the new server.

As you wrote in readme I did this:

1. did a new setup and created new email with the new server connection
2. created the folder to match the new email but without run the backup
3. copied the inbox.mbox and inbox.imap to the folder of the new mail
4. run the restore with this command: `imap-backup restore my@email.com`

It fails with this error:

`/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/imap.rb:1221:in `get_tagged_response': Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.001 + 0.038 + 0.037 secs). (Net::IMAP::NoResponseError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/imap.rb:1275:in `block in send_command'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/imap.rb:1257:in `send_command'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/imap.rb:481:in `create'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `create'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/gems/imap-backup-6.3.0/lib/imap/backup/account/folder.rb:44:in `create'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/gems/imap-backup-6.3.0/lib/imap/backup/uploader.rb:68:in `rename_serialized_folder'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/gems/imap-backup-6.3.0/lib/imap/backup/uploader.rb:13:in `run'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/gems/imap-backup-6.3.0/lib/imap/backup/account/connection.rb:83:in `block in restore'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/gems/imap-backup-6.3.0/lib/imap/backup/account/connection.rb:77:in `block in local_folders'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/gems/imap-backup-6.3.0/lib/imap/backup/account/connection.rb:73:in `glob'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/gems/imap-backup-6.3.0/lib/imap/backup/account/connection.rb:73:in `glob'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/gems/imap-backup-6.3.0/lib/imap/backup/account/connection.rb:73:in `local_folders'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/gems/imap-backup-6.3.0/lib/imap/backup/account/connection.rb:82:in `restore'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/gems/imap-backup-6.3.0/lib/imap/backup/cli/restore.rb:20:in `run'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/gems/imap-backup-6.3.0/lib/imap/backup/cli.rb:120:in `restore'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/gems/imap-backup-6.3.0/bin/imap-backup:14:in `block in <top (required)>'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/gems/imap-backup-6.3.0/lib/imap/backup/logger.rb:29:in `sanitize_stderr'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/gems/imap-backup-6.3.0/bin/imap-backup:13:in `<top (required)>'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/bin/imap-backup:23:in `load'
	from /opt/homebrew/Cellar/imap-backup/6.3.0/libexec/bin/imap-backup:23:in `<main>'`

any help would be apreciated

**Comment by joeyates** [comment]
Hi @metanodotto 

Please try the [migrate](https://github.com/joeyates/imap-backup/blob/main/docs/commands/migrate.md) command, which allows you to specify IMAP namespaces ('prefixes') when moving from one service to another.

**Comment by metanodotto** [comment]
hi @joeyates 

The old imap is closed. All I have is a local backup done with your imap-backup.

the new one is not empty anymore because it has received mail in the past 4 days.

So I read in the help that migrate command (if I correctly understood) works with 2 active accounts (that I don't have) and that it stops with error if destination is not empty (my destination is not empty and I have to keep new mails).

could you help me?

**Comment by joeyates** [comment]
@metanodotto Any progress on this?
