### ISSUE TITLE
Feature request: Logging levels

### ISSUE THREAD

**Issue by jacobrharris** [joeyates/imap-backup#130]
I need some amount of logging, but `"debug": true` is a bit of a firehose and seems to be the only option. Any plans for supporting more logging levels or some other way of tuning how much gets printed?

**Comment by joeyates** [comment]
Hi @jacobrharris 

Switching to comand-line switch controlled verbosity levels is second on the road map - after the addition of the mirror command! Watch this space :)

**Comment by joeyates** [comment]
@jacobrharris 

I've just release version 7.0.2 with comand-line-controllable logging levels.

The default logging level is now 'info' instead of 'error', so you get some output when running backups.
The `--verbose` flag turns on debugging output, while the `--quiet` flag stops all output.
