### ISSUE TITLE
Is version 7.0.0 an official release?

### ISSUE THREAD

**Issue by iMichka** [joeyates/imap-backup#131]
Hi. Homebrew maintainer here.

We noticed that the 7.0.0 tag was pushed, but no release published on GitHub.
In general this is a sign that this is a pre-release and should not be used / the tag might still move.

We would like to confirm this with you before shipping 7.0.0 to our users.

See for reference: https://github.com/Homebrew/homebrew-core/pull/109531

**Comment by joeyates** [comment]
Hi @iMichka 

You are correct: 7.0.0 should **not** be shipped to Hoomebrew users yet.

I now realize that pushing tags can have this outcome, so in future I'll avoid pushing them until the moment of release!

**Comment by iMichka** [comment]
Thanks, no issue. What you could to is tag it with "7.0.0-rc1" or "7.0.0-beta" (or something similar). The tag can later be dropped if you wish, or kept for historical reasons. We will not ship the update until a proper release has been created on your side.
