### ISSUE TITLE
Documentation insufficient

### ISSUE THREAD

**Issue by bdynamic** [joeyates/imap-backup#132]
The Link mentioned on this page is dead:
https://github.com/joeyates/imap-backup/blob/main/docs/configuration.md

Unfortunately it is unclear how to config a server for usage of  STARTTLS on Port 143. Default seems to be SSL/TLS on port 993.

Thanks for the support and for this project
Birk

**Comment by joeyates** [comment]
I've corrected the link, thanks.

The page https://github.com/joeyates/imap-backup/blob/main/docs/configuration.md now has a link to the [Ruby Standard Library documentation for the configuration that can be set](https://ruby-doc.org/stdlib-3.1.2/libdoc/net-imap/rdoc/Net/IMAP.html#method-c-new).
