### ISSUE TITLE
Problems with migrate and restore

### ISSUE THREAD

**Issue by tezakaftor** [joeyates/imap-backup#133]
Hi!
I'm trying imap-backup and I'm not able to restore or migrate mails from an account to a new test account on my mail server (cpanel). I'm just getting the error message shown below:

`W, [2022-09-24T16:21:44.608884 #2338822]  WARN -- : [INBOX] uid: 341 (1/3) - append error: Error in IMAP command APPEND: Invalid system flag \$NOTJUNK (0.001 + 0.003 + 0.002 secs).
W, [2022-09-24T16:21:44.625444 #2338822]  WARN -- : [INBOX] uid: 342 (2/3) - append error: Error in IMAP command APPEND: Invalid system flag \$NOTJUNK (0.001 + 0.003 + 0.002 secs).
W, [2022-09-24T16:21:44.641930 #2338822]  WARN -- : [INBOX] uid: 343 (3/3) - append error: Error in IMAP command APPEND: Invalid system flag \$NOTJUNK (0.001 + 0.003 + 0.002 secs).`

Is there a solution to this?

**Comment by joeyates** [comment]
Hi @tezakaftor 

I've just released version 8.0.1 with a fix for this.
