### ISSUE TITLE
allow migrate without reset flag

### ISSUE THREAD

**Issue by maty974** [joeyates/imap-backup#142]
Hi @joeyates 

I'm still in the same case as my previous [issue](https://github.com/joeyates/imap-backup/issues/140), I need to migrate mail accounts to the same domain name.

- I was wondering if the `migrate` command can be used without the `--reset` flag, with the same behaviour as the `restore` command where newly arrived mails left untouched from the destination server during the `restore`

In the case of a domain transfert to the same domain name to another host provider, I will create new empty target mail accounts on the new hosting provider, but before I do the `migrate` command it is possible that new mails arrive in the new empty mail box and cannot be backed up before migration is done

To avoid loosing theses newly arrived mails the `--reset` flag is problematic while using the `migrate` command

I hope my explanations are clear and a solution is available for again this (not so?) special case :smiley: 

Thanks again :pray:

**Comment by joeyates** [comment]
@maty974 I'll have another look at the `migrate` command to see if it is really necessary to require that the destination folder is empty.

IIRC, it was originally intended to avoid the mess of repeated migrations causing multiple copies of emails to end up on the destination server. If that is the *only* reason why there's this requirement, the `--reset` flag can become optional.

**Comment by maty974** [comment]
Hi @joeyates 

That would be awesome thanks! let me know if I can test it ;)

**Comment by joeyates** [comment]
@maty974 

I've release this as v9.0.1.rc1. Let me know if you get a chance to test it. Thanks!

**Comment by maty974** [comment]
Hi @joeyates !

Yeah it seems to work fine :+1: 

Do the `migrate` command use the option like `multi_fetch_size` ? 
It seems to be very slow compared to the `backup` command

Thanks again for your help

**Comment by maty974** [comment]
@joeyates my fault, something was limiting my VM traffic 👌

everything seems to be fine, without the now optional `—reset` argument 

thanks 🙏
