### ISSUE TITLE
Migration does not end - EOF error

### ISSUE THREAD

**Issue by SRLive** [joeyates/imap-backup#144]
EDIT - Wrongly identified issue so changing post

Hi, I'm experiencing a strange issue here.  I've run imp-backup for a month now and I need to migrate a mailbox.

So I used the migrate option but I got an "end of file reached (EOFError)" error.  This seems to be a connection issue since if I restart the command, it stopped on another folder.

I tried to run in verbose but I get an argument error.  How could I help find what's the problem?

**Comment by joeyates** [comment]
Hi @SRLive 

Thanks for opening the issue.

First of all, please post the verbose output with the argument error.

**Comment by joeyates** [comment]
Thanks @SRLive 

Could you also include the command you are using.

Please ensure that you are passing the `--verbose` option.

As the formatting got a bit confused in your previous comment, please also re-post the output.

**Comment by SRLive** [comment]
mmmh, no verbose for the migrate command it seems...

`backuper@backuper:~$ imap-backup migrate info@ecrin.be contact@ecrin.be --reset --verbose`
`Traceback (most recent call last):`
`	11: from /usr/local/bin/imap-backup:23:in '<main>'`
`	10: from /usr/local/bin/imap-backup:23:in 'load'`
`	 9: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/bin/imap-backup:11:in '<top (required)>'`
`	 8: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/logger.rb:34:in 'sanitize_stderr'`
`	 7: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/bin/imap-backup:12:in 'block in <top (required)>'`
`	 6: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in 'start'`
`	 5: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in 'dispatch'`
`	 4: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in 'invoke_command'`
`	 3: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in 'run'`
`	 2: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/cli.rb:109:in 'migrate'`
`	 1: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/cli.rb:109:in 'new'`
`/var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/cli/migrate.rb:15:in 'initialize': unknown keyword: :verbose (ArgumentError)`

(MMMh, there is a lot of the same character as the code function, maybe I should pass a text file instead of editing for formatting...)

**Comment by SRLive** [comment]
Without verbose and correct formatting : 

`backuper@backuper:~$ imap-backup migrate info@ecrin.be contact@ecrin.be --reset`
`W, [2023-01-18T22:09:50.128535 #11094]  WARN -- : Folder 'INBOX.Locations et résidences.Locations Résidences 2020.EAG' does not exist on server`
`W, [2023-01-18T22:10:09.069634 #11094]  WARN -- : Folder 'INBOX.Junk' does not exist on server`
`W, [2023-01-18T22:10:09.438146 #11094]  WARN -- : Folder 'INBOX.Éléments supprimés.Après AG envois officiels 2022' does not exist on server`
`W, [2023-01-18T22:10:09.794430 #11094]  WARN -- : Folder 'INBOX.Remorque publicitaire.Betons Bouffioux' does not exist on server`
`W, [2023-01-18T22:10:14.946547 #11094]  WARN -- : Folder 'INBOX.Locations et résidences.Locations Résidences 2021.CNL' does not exist on server`
`W, [2023-01-18T22:10:15.699530 #11094]  WARN -- : Folder 'INBOX.Locations et résidences.Locations Résidences 2022.Vinobby' does not exist on server`
`W, [2023-01-18T22:10:16.591478 #11094]  WARN -- : Folder 'INBOX.Éléments supprimés.2020-2021 BILLETTERIE' does not exist on server`
`W, [2023-01-18T22:10:19.878526 #11094]  WARN -- : Folder 'INBOX.Éléments supprimés.COGES AG 2020' does not exist on server`
`W, [2023-01-18T22:10:43.891989 #11094]  WARN -- : Folder 'INBOX.Éléments supprimés.2021-2022 A TRAITER bal' does not exist on server`
`W, [2023-01-18T22:10:44.255827 #11094]  WARN -- : Folder 'INBOX.Locations et résidences.Locations Résidences 2020.JDD' does not exist on server`
`Traceback (most recent call last):`
`	25: from /usr/local/bin/imap-backup:23:in '<main>'`
`	24: from /usr/local/bin/imap-backup:23:in 'load'`
`	23: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/bin/imap-backup:11:in '<top (required)>'`
`	22: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/logger.rb:34:in 'sanitize_stderr'`
`	21: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/bin/imap-backup:12:in 'block in <top (required)>'`
`	20: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in 'start'`
`	19: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in 'dispatch'`
`	18: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in 'invoke_command'`
`	17: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in 'run'`
`	16: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/cli.rb:109:in 'migrate'`
`	15: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/cli/migrate.rb:35:in 'run'`
`	14: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/cli/migrate.rb:35:in 'each'`
`	13: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/cli/migrate.rb:62:in 'folders'`
`	12: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/cli/migrate.rb:62:in 'glob'`
`	11: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/cli/migrate.rb:62:in 'glob'`
`	10: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/cli/migrate.rb:66:in 'block in folders'`
`	 9: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/cli/migrate.rb:36:in 'block in run'`
`	 8: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/migrator.rb:15:in 'run'`
`	 7: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/account/folder.rb:45:in 'create'`
`	 6: from /usr/lib/ruby/2.7.0/forwardable.rb:235:in 'create'`
`	 5: from /var/lib/gems/2.7.0/gems/net-imap-0.3.2/lib/net/imap.rb:590:in 'create'`
`	 4: from /var/lib/gems/2.7.0/gems/net-imap-0.3.2/lib/net/imap.rb:1484:in 'send_command'`
`	 3: from /usr/lib/ruby/2.7.0/monitor.rb:202:in 'mon_synchronize'`
`	 2: from /usr/lib/ruby/2.7.0/monitor.rb:202:in 'synchronize'`
`	 1: from /var/lib/gems/2.7.0/gems/net-imap-0.3.2/lib/net/imap.rb:1502:in 'block in send_command'`
`/var/lib/gems/2.7.0/gems/net-imap-0.3.2/lib/net/imap.rb:1434:in 'get_tagged_response': end of file reached (EOFError)`

**Comment by joeyates** [comment]
@SRLive Is this still an active issue, or can we close?
