### ISSUE TITLE
About tag 9.0.2

### ISSUE THREAD

**Issue by chenrui333** [joeyates/imap-backup#147]
👋 Just raise this issue to confirm whether 9.0.2 is the latest release, seeing in rubygems, but not the `latest` release. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/122527

**Comment by joeyates** [comment]
Hi @chenrui333 

Yes, 9.0.2 **is** the latest release.

**Comment by chenrui333** [comment]
@joeyates thanks for confirming it, can you mark that tag as `latest` release? Thanks!! 🙏

**Comment by chenrui333** [comment]
oh, i actually mean the github release rather than git tag

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/1580956/218439428-4cd0ff4e-00d9-4b0f-a2eb-2db722ad19ac.png">

**Comment by joeyates** [comment]
OK, clear now. I've cut a new `latest` release.
