### ISSUE TITLE
Backup fails if a Mailbox Folder contains invalid filesystem characters 

### ISSUE THREAD

**Issue by schittli** [joeyates/imap-backup#151]
Good evening
**thank you very much for sharing your great work!**

I have a probably small bug report:
If the mailbox contains a folder like `50 Triage: Emergency
then `imap-backup` fails with:

```
Backup for account '…' failed with error: Not a directory @ dir_s_mkdir
```

I'm pretty sure it tries to create a folder with the `:` character which, of course, does not work.

Therefore, `imap-backup` needs a mapping logic to convert between imap folder characters, which are invalid on a filesystem.

Thanks a lot, kind regards,
Thomas

**Comment by joeyates** [comment]
Hi @schittli 

Thanks for opening the issue.

I've added a fix for this in [release 9.2.0](https://github.com/joeyates/imap-backup/releases/tag/v9.2.0).
