### ISSUE TITLE
Usage of Thunderbird Export unclear

### ISSUE THREAD

**Issue by nicnab** [joeyates/imap-backup#155]
Calling "help utils export-to-thunderbird" does not work. I'm unsure about the command line parameters necessary - in addition to the email account.

(Other than that imap-backup is very handy and seems to work well - thank you!)

**Comment by joeyates** [comment]
Hi @nicnab 

As an initial answer, to get help, use this command:

```sh
imap-backup utils help export-to-thunderbird
```

It's a bit weird, I know, but `help` has to be the penultimate part of the command

**Comment by nicnab** [comment]
Great, thanks for the quick answer! This is a little unclear in the documentation.

**Comment by joeyates** [comment]
@nicnab I've released version [9.3.1](../releases/v9.3.1) which should do what users expect.

Now, this
```sh
imap-backup help utils export-to-thunderbird
```

works like the default
```sh
imap-backup utils help export-to-thunderbird
```

and shows the help for the subcommand method.

**Comment by Weiming-Hu** [comment]
I'm going through the same confusion.

**Comment by joeyates** [comment]
@michaldejmek and @Weiming-Hu 

Please see #161 for some more info on this.

**Comment by Weiming-Hu** [comment]
Hi @joeyates, thank you very much for your reply.

After upgrading to 10.0.1 and 
1. Set up my first Thunderbird account
2. Run the export account,
I can see that the exported folders are correctly shown.

I still need to set the correct local folder in Thunderbird before I can actually see these mails. But this is just a simple setting in Thunderbird.

Much appreciated for the help and awesome tool!
