### ISSUE TITLE
IMPORT mbox

### ISSUE THREAD

**Issue by michaldejmek** [joeyates/imap-backup#161]
Hi, thanks for the great tool. 

**I have a few questions:**

- The export of the email is done OK, is there a log if any email is omitted .?
- I'm trying to import a file into Thunderbird using "ImportExport Tools NG" - but the folder structure is different than on the original server.  Now it is INBOX.TEST, but originally it should be INBOX and subfolder TEST. 
- would it be possible to remove the word mbox after importing it to "Thunderbird" example: INBOX.TEST.mbox ..?

Regarding the export to "Thunderbird" function, after running imap-backup utils export-to-thunderbird xx a new profile is created .? Or just copy the data from the .imap-backup/xx folder to the current profile .?

Thank you Michal.

**Comment by joeyates** [comment]
Hi @michaldejmek

By default, `export-to-thunderbird` exports to the default profile.
When exporting to Thunderbird, it modifies mailboxes to make them compatible with Thunderbird. 
It does *not* export mailboxes with the `.mbox` extension.

I've just released version 10.0.0 of imap-backup.

Now, during export, you will see the paths where folders have been exported to.

Also, now, `export-to-thunderbird` requires that Thunderbird has at least one account set up. The program now halts if no account is found.
