### ISSUE TITLE
Backup for account 'xxxx' failed with error undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by michaldejmek** [joeyates/imap-backup#164]
The mailbox has around 50GB. 

rewind(tsx.data[:savepoint][:length])
                     ^^^^^^^^^^^^
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/serializer/mbox.rb:36:in `rollback'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/serializer/mbox.rb:27:in `rescue in block in transaction'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/serializer/mbox.rb:20:in `block in transaction'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/serializer/transaction.rb:17:in `begin'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/serializer/mbox.rb:19:in `transaction'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/serializer/delayed_metadata_serializer.rb:25:in `block in transaction'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/serializer/transaction.rb:17:in `begin'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/serializer/delayed_metadata_serializer.rb:24:in `transaction'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/account/backup.rb:61:in `block in run'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/account/backup.rb:89:in `block in each_folder'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/account/backup_folders.rb:37:in `block in each'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/account/backup_folders.rb:37:in `each'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/account/backup_folders.rb:37:in `each'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/account/backup.rb:87:in `each_folder'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/account/backup.rb:30:in `run'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/cli/backup.rb:24:in `block in run'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/cli/backup.rb:22:in `each'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/cli/backup.rb:22:in `run'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/cli.rb:72:in `backup'
/var/lib/gems/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
/var/lib/gems/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
/var/lib/gems/3.1.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
/var/lib/gems/3.1.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/cli.rb:45:in `start'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/bin/imap-backup:12:in `block in <top (required)>'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/lib/imap/backup/logger.rb:41:in `sanitize_stderr'
/var/lib/gems/3.1.0/gems/imap-backup-11.0.0/bin/imap-backup:11:in `<top (required)>'
/usr/local/bin/imap-backup:25:in `load'
/usr/local/bin/imap-backup:25:in `<main>'

**Comment by joeyates** [comment]
Thanks @michaldejmek I'll be releasing a fix shortly.
