### ISSUE TITLE
Make .mbox.gz files (or other compression format)

### ISSUE THREAD

**Issue by frabcus** [joeyates/imap-backup#168]
Mailbox files compress really well, so ideally I'd like `imap-backup` to just directly write `mbox.gz` files instead of `mbox` files. This would probably speed it up too, and makes backups much smaller.

Only if it is smooth and easy and would just work - depends on what Ruby compression libraries there are, and how much imap-backup seek sin the file.

**Comment by joeyates** [comment]
Hi @frabcus 

I think compressing mailboxes would be an interesting enhancement.

PRs, as always are welcome :tm:, but I think this would need to be an optional, rather than the default behaviour :)

**Comment by joeyates** [comment]
I'll close for now, but am open to PRs which implement this :)
