### ISSUE TITLE
Why is migrate different from backup & restore?

### ISSUE THREAD

**Issue by axelsimon** [joeyates/imap-backup#170]
Hello!
The docs [page on restore](https://github.com/joeyates/imap-backup/blob/main/docs/commands/restore.md) says:
> If you are switching to a new e-mail provider, but want to keep your existing e-mail address, it is best to use the [migrate](https://github.com/joeyates/imap-backup/blob/main/docs/commands/migrate.md) command instead of restore. See [this guide on the topic](https://github.com/joeyates/imap-backup/blob/main/docs/migrate-server-keep-address.md).

and in [this comment](https://github.com/joeyates/imap-backup/issues/113#issuecomment-1030863904) , introducing the migrate commande, you say:
> As the requirements of a restore a different from a migration, I have opted for a separate command.

but the difference as far as i can tell is never explained :slightly_smiling_face: 

In my specific case, i'm moving a domain from Gandi to OVH,  and backing up an email account that was hosted by Gandi, who were up until now the registrar for the email's domain. Currently, i can't yet recreate the email account on OVH, as the domain hasn't finished transfering. Once the domain is has transfered to OVH, the original account will no longer accessible. In short, the two email accounts will never exist at the same time, which means backup, wait, restore.

Put a different way, as far as i can tell you can't migrate user@example.com (hosted by X) to user@example.com (hosted by Y) because the two accounts won't be valid at the same time.

I imagine migrate is not for this case, but clarification as to what it does would be helpful i think :)

**Comment by joeyates** [comment]
@axelsimon I've added a short explanation to [the guide](https://github.com/joeyates/imap-backup/blob/6bd572b468cc08ffc504616af09bd4adb88b9586/docs/migrate-server-keep-address.md).

**Comment by axelsimon** [comment]
Very cool, thanks @joeyates !
