### ISSUE TITLE
iCloud: Messages are marked as unread regardless of setting

### ISSUE THREAD

**Issue by glocknerc** [joeyates/imap-backup#177]
I found #118, but it seems in 13.0.0 the issue still (or again) exists. Interestingly there is a difference in behaviour that I observed:

1. A completely new e-mail never previously read will be marked as read once imap-backup runs
2. A previously read e-mail manually marked as unread will not be marked as read once imap-back runs

The behaviour is the same, regardless of the `fix changes to unread flags during download` setting

**Comment by joeyates** [comment]
Hi @glocknerc 

Thanks for opening the issue. I've found the cause and will be releasing a fix soon!

**Comment by joeyates** [comment]
I've release version 13.1.0 with a fix.
