### ISSUE TITLE
`uninitialized constant Imap::Backup::VERSION` with 13.3.0 release build

### ISSUE THREAD

**Issue by chenrui333** [joeyates/imap-backup#179]
👋 While trying to [the latest release build](https://github.com/Homebrew/homebrew-core/pull/149910), ie 13.3.0, I ran into some test failure as below:

```
/opt/homebrew/Cellar/imap-backup/13.3.0/libexec/gems/imap-backup-13.3.0/lib/imap/backup/cli.rb:265:in `version': uninitialized constant Imap::Backup::VERSION (NameError)

      Kernel.puts "imap-backup #{Imap::Backup::VERSION}"
                                             ^^^^^^^^^
```

Commands are:
- `imap-backup version`
- `imap-backup --version`

relates to https://github.com/Homebrew/homebrew-core/pull/149910

**Comment by joeyates** [comment]
I've release version 13.4.0 to fix this

**Comment by chenrui333** [comment]
Thanks @joeyates, gonna try it now.

**Comment by chenrui333** [comment]
works for me, thanks for the quick turnaround! 💯
