### ISSUE TITLE
Miration failed with "Character not allowed in mailbox name"

### ISSUE THREAD

**Issue by slgfire** [joeyates/imap-backup#199]
Hello,
i try to migrate local backup with filename like Bestellungen.Hardware.Netzwerk.imap and Bestellungen.Hardware.Netzwerk.mbox

on the old imap account that was a folder like Bestellungen/Hardware/Netzwerk

when i try 

`docker run -v ./my-config:/config -v ./:/data -ti ghcr.io/joeyates/imap-backup:latest \
  imap-backup migrate name-old@mail.com name@mail.com -c /config/imap-backup.json
`

migration failes with "Character not allowed in mailbox name: '.'"

i try source-prefixes="." and source-delimiter="." but the same error.

what can i do?

thanks for help!

**Comment by joeyates** [comment]
Hi @slgfire 

I think it's the `destination-prefix` that you need to set. Try using the `imap-backup remote namespaces EMAIL` command to see what delimiter is used on "name@mail.com"
