### ISSUE TITLE
Single Backup with relying on configuration file

### ISSUE THREAD

**Issue by martinpichlo** [joeyates/imap-backup#205]
Hi,

is it possible, to create a backup just for a single account within configuration?

I found "imap-backup single backup ...", but it ignores the configuration. 

I'm looking for a command like "imap-backup backup EMAIL" or "imap-backup single backup EMAIL", which reads the configuration.

**Comment by joeyates** [comment]
Hi @martinpichlo 

You can use the `--accounts` parameter to the `backup` command.

I.e.

```sh
imap-backup backup --accounts=me@example.com
```

Check out the full help for the command like this

```sh
imap-backup help backup
``
