### ISSUE TITLE
Error during backup:  incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by galmok** [joeyates/imap-backup#207]
While backing up my inbox, I received this message twice:

E, [2024-07-24T10:00:45.983931 #189] ERROR -- : [INBOX] incompatible character encodings: UTF-8 and ASCII-8BIT
E, [2024-07-24T10:00:49.299734 #189] ERROR -- : [INBOX] incompatible character encodings: UTF-8 and ASCII-8BIT

The backup continued on its own, but what does that mean in regards to my backup?
Are messages lost, or is this more like a warning and not an error?

**Comment by joeyates** [comment]
Hi @galmok 

This seems to happen with certain email server setups. The way that the email text is encoded is not compatible with the standards and imap-backup doesn't know how to treat the single message. In this case, the specific message is skipped and the rest of the backup continues.
