### ISSUE TITLE
Migrate full automation

### ISSUE THREAD

**Issue by btxtiger** [joeyates/imap-backup#208]
Hey there,
I have to migrate about 60 Mail Accounts to a new provider while keeping (also transferring) the Domain. 
The process described [here](https://github.com/joeyates/imap-backup/blob/main/docs/howto/migrate-server-keep-address.md) is clear, however I can not do the manual steps without automation, I would simply take too much time. Unfortunately I can not make a direct transfer, since the domain has to be transferred first, after which I can create the new inboxes.

What do you think would be an acceptable solution for this?
I was thinking about creating a shell script, that renames all domains to "@domain-old" since this could be easily done using string replacement. Would this also work? In your example you renamed the inbox name instead.

Many thanks

**Comment by joeyates** [comment]
The idea that comes to mind is to load the JSON config file in a script that parses it and makes the necessary substitutions. If the changes are regular, I imagine it could be done quite simply.

**Comment by btxtiger** [comment]
@joeyates Thank I'll try it and share the final script, so you might add it to the docs.

Another question would be if it is possible to restore a mailbox into a subfolder of the new mailbox, since I also have to merge some mail accounts and dont want to mess up the mails.

**Comment by joeyates** [comment]
You can use the `--destination-prefix` param when running the migration to change the folder path.

**Comment by btxtiger** [comment]
The test worked pretty good. I'll share the final script as PR
Thanks
