### ISSUE TITLE
Unparsable Response

### ISSUE THREAD

**Issue by kingofomidia** [joeyates/imap-backup#213]
Hi, I'm using imap-backup through davmail to backup an exchange thing on office 365.  I've authenticated, it seems imap-backup grabs a list of the folders...  a few times for some reason, and then exists "ERROR -- Backup for account 'user@domain.ca" failed with error unparsable response". I can't figure out what's going on except maybe there's a folder name it doesn't like in the list?  But I can't see anything all that bizarre.  Slashes, spaces, the usual one might expect are there, but those should be fine...  Any thoughts?  Thanks!

**Comment by kingofomidia** [comment]
So here's some additional info. After it lists the folders, this is the exchange that happens (captured with tcpdump) before it exits out with the error. I don't know enough to know what of this is unparsable...:

RUBY0005 OK LIST completed
RUBY0006 EXAMINE Archive
*  633 EXISTS
* 0 RECENT
* OK [UIDVALIDITY 1]
* OK [UIDNEXT 794]
* FLAGS (\Answered \Deleted \Draft \Flagged \Seen $Forwarded Junk)
* OK [PERMANENTFLAGS (\Answered \Deleted \Draft \Flagged \Seen $Forwarded Junk \*)]
RUBY0006 OK [READ-ONLY] EXAMINE completed

**Comment by joeyates** [comment]
Hi @kingofomidia 

The best way to diagnose these things is to activate verbose mode.

E.g.

```sh
imap-backup backup --verbose --verbose
```

With `--verbose` twice you get imap-backup's debug output and all network traffic.

**Comment by kingofomidia** [comment]
Hi, thanks for the reply!  So eventually I moved off of davmail and onto emailproxy to log into microsoft 365, with better results.  I am having a different issue though.  I'll open a new issue about it.  I guess I wish there was an active user forum that I could ask in.  In the meantime, I very much appreciate your guidance!

**Comment by kingofomidia** [comment]
Let me add, if you would like me to try davmail again to reproduce the error with the suggestion you offered (the verbose flag) for reasons, I'm happy to.  I just have no need to for my own purposes... but I'm happy to if it supports the thing!

**Comment by joeyates** [comment]
Thanks @kingofomidia 

I've taken up your idea of a user forum. I've activated [GitHub Discussions](https://github.com/joeyates/imap-backup/discussions) :tada:
