### ISSUE TITLE
backup fails due to bad message?

### ISSUE THREAD

**Issue by quantitative-technologies** [joeyates/imap-backup#218]
I am trying to backup yahoo mail. My [Inbox] folder has a large number of messages > 100,000.

After downloading a couple of thousand, `imap-backup` is stuck:

```console
...
D, [2024-11-17T10:18:15.946085 #77249] DEBUG -- : [Inbox] running backup
I, [2024-11-17T10:18:26.308831 #77249]  INFO -- : [Inbox] 95330 new messages
E, [2024-11-17T10:18:31.290994 #77249] ERROR -- : Backup for account 'XXXX@yahoo.com' failed with error UID FETCH Server error - Please try again later
...
```

My config has

```
  "download_strategy": "direct"
```

So it is not starting from the beginning each time. 

How can I deal with this, so I can download the other messages?

**Comment by joeyates** [comment]
I suspect you're hitting a rate limit.

You *may* be able to make the block size larger, e.g.

```json
"multi_fetch_size": 100
```

But, first of check online about "Yahoo IMAP rate limiting".

**Comment by quantitative-technologies** [comment]
Hello @joeyates 

I don't believe it has anything to with rate limits at all:

Once it is stuck, it cannot even download a single email. Even if I wait until the next day.

I confirmed this by removing the mbox file, and then running backup again. It download the first `2507` messages and then hits the error:

```console
D, [2024-11-18T09:43:39.003684 #87156] DEBUG -- : [Inbox] uid: 32910 (2504/100000) - 7151 bytes
D, [2024-11-18T09:43:39.958660 #87156] DEBUG -- : [Inbox] uid: 32911 (2505/100000) - 26122 bytes
D, [2024-11-18T09:43:40.933643 #87156] DEBUG -- : [Inbox] uid: 32912 (2506/100000) - 14470 bytes
D, [2024-11-18T09:43:42.162624 #87156] DEBUG -- : [Inbox] uid: 32913 (2507/100000) - 11465 bytes
E, [2024-11-18T09:43:47.078024 #87156] ERROR -- : Backup for account 'XXXX@yahoo.com' failed with error UID FETCH Server error - Please try again later
```

Now, if I run it again after the failure, no further messages can be downloaded since it seems to get stuck on message `2508`:

```console
D, [2024-11-18T09:51:53.377001 #88750] DEBUG -- : [Inbox] running backup
I, [2024-11-18T09:52:05.056755 #88750]  INFO -- : [Inbox] 97493 new messages
E, [2024-11-18T09:52:10.009112 #88750] ERROR -- : Backup for account 'XXXX@yahoo.com' failed with error UID FETCH Server error - Please try again later
```

Is the `uid` something I can identify in the web mail interface to locate the problematic message? (Assuming that is actually the issue here.)

**Comment by joeyates** [comment]
Hi @quantitative-technologies 

In order to identify the message via the webmail interface, you can list the message(s) downloaded before it:

```sh
imap-backup local list 'XXXX@yahoo.com' Inbox
```

**Comment by quantitative-technologies** [comment]
Cool! So far I have found 2 messages in the Inbox which could not be loaded in the web interface either. Once deleted the backup was able to proceed. Still in progress...

Thanks.

**Comment by joeyates** [comment]
Good news!
