### ISSUE TITLE
base folder is created with wrong permissions and never changed

### ISSUE THREAD

**Issue by jeffhawke** [joeyates/imap-backup#29]
If the base folder does not exist and the umask is not set correctly, the Utils.make_folder creates it but does not set the permissions and the program then crashes when the permissions are checked later.

A line need to be added just before the parts.each loop at line 28 of utils.rb:

FileUtils.chmod permissions, path

This correctly sets the pemissions for the base folder.

**Comment by joeyates** [comment]
`imap-backup` only "lays claim" to the directory containing config and backup directories, so I resolved this in a different way to the one you suggested.
The config path should be the highest level directory that `imap-backup` creates and/or manages in terms of permissions. If *that* directory does not exist, it is created and the correct permissions are set. If the containing directory does not exists, then it fails.
The check on permissions of the config directory was redundant so I've removed it.
