### ISSUE TITLE
"Hostname does not match the server certificate" error 

### ISSUE THREAD

**Issue by swarzynski** [joeyates/imap-backup#31]
Hi, I have mailbox on my mydomain.nazwa.pl provider server which I bought.
Adress is a.swarzynski@mydomain.nazwa.pl. 
When I try test connection I get:

```
D, [2016-04-23T14:54:55.065012 #17069] DEBUG -- : Creating IMAP instance: imap.mydomain.nazwa.pl, options: {:port=>993, :ssl=>true}
Unexpected error: hostname "imap.mydomain.nazwa.pl" does not match the server certificate
```

Thunderbird at account configuration also complained about certificate at first but I added exception (button in Thunderbird) and it worked.
Is it possible to bypass this error?

**Comment by joeyates** [comment]
I've created a branch 'feature/connection-overrides' with code which allows SSL configuration to be manually added to the config file. 

If you can help me debug this:
1. check out the source code,
2. switch to the 'feature/connection-overrides' branch,
3. modify your `~/.imap-backup/config.json` following the 'Connection options' section in the README,
4. try running the connection test from the CLI (choose your account, then 'test connection')

**Comment by joeyates** [comment]
Closing due to lack of response.
Please reopen is you want to try debugging the issue.
