### ISSUE TITLE
Backup only to ~/.imap-backup possible

### ISSUE THREAD

**Issue by AntonTrapp** [joeyates/imap-backup#33]
The program is working fine as long as I do not set a custom path.

Any other path (no matter if edited in the config file or via setup and menus is completely ignored, the mail-directories to backup are created in ~/.imap-backup and after that the program freezes. If interrupted it shows the following:

`/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:111:in`sleep': Interrupt
    from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:111:in `wait'
    from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:111:in`wait'
    from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:1191:in `get_tagged_response'
    from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:1250:in`block in send_command'
    from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:1232:in`send_command'
    from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:467:in `block in examine'
    from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in`mon_synchronize'
    from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:465:in `examine'
    from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/account/folder.rb:35:in`fetch'
    from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/downloader.rb:16:in `block in run'
    from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/downloader.rb:15:in`each'
    from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/downloader.rb:15:in `run'
    from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/account/connection.rb:44:in`block in run_backup'
    from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/account/connection.rb:69:in `block in each_folder'
    from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/account/connection.rb:66:in`each'
    from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/account/connection.rb:66:in `each_folder'
    from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/account/connection.rb:42:in`run_backup'
    from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/bin/imap-backup:67:in `block in <top (required)>'
    from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/configuration/list.rb:21:in`block in each_connection'
    from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/configuration/list.rb:19:in `each'
    from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/configuration/list.rb:19:in`each_connection'
    from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/bin/imap-backup:66:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/bin/imap-backup:23:in`load'
    from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/bin/imap-backup:23:in `<main>'
    from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/bin/ruby_executable_hooks:15:in`eval'
    from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/bin/ruby_executable_hooks:15:in `<main>'`

ruby 2.3.0, imap-backup (1.1.0)  in own gemset (rvm)

**Comment by joeyates** [comment]
Thanks for the bug report.

1. Could you confirm that your connection definitely works:
```
$ imap-backup setup
```
then choose the account from the menu,
then 'test connection'.
 
2. Could you anonymize your config file (~/.imap-backup/config.json) and send it to me (the best way is via a private Gist)?
3. Also, please try turning on debugging (add `"debug": true` to your config as indicated in the README) and send me the (anonymized) result.

**Comment by joeyates** [comment]
Thanks for the bug report.

I've been able to replicate the problem. I'll let you know when it's fixed.

**Comment by AntonTrapp** [comment]
Happy that I can help. Using it with standard directory in my mail backup script at the moment. Really awesome! TNX for this tool!!!

**Comment by joeyates** [comment]
This is fixed in f48b9b6564c3692dd6205f3ef4b474c814624cea
I've released version 1.2.1 with the fix.
