### ISSUE TITLE
Email validation does not allow gTLDs

### ISSUE THREAD

**Issue by flungo** [joeyates/imap-backup#38]
The email validation used when running the interactive setup considers emails which use gTLDs to be invalid. To reproduce, try adding an account with the email `example@example.solutions` which should be a completely valid email address but gets the error:

> Enter a valid email address ?  email address: ||

Manually adding the account to the configuration works exactly as expected.

**Comment by joeyates** [comment]
Thanks for letting me know. I'll have a look asap.

**Comment by joeyates** [comment]
This is fixed in d2e1fb0a33b4a5b84a6527def6af3880a2ddc4d5
I've released version 1.2.0 with the fix.
