### ISSUE TITLE
All folders

### ISSUE THREAD

**Issue by grodansparadis** [joeyates/imap-backup#39]
Is there a way to select "all folders" in the setup. Hard to select each subfolder if you have +300 folders as I have.

**Comment by joeyates** [comment]
Hello,

"All folders" certainly makes sense as an option.

I'll have a look at how much work would be involved.

As a stopgap, if it's a GMail account, you obviously get a copy of everything with 'All Mail' - but, clearly you lose all filtering and manual sorting you've done.
