### ISSUE TITLE
Backing up Calendar folder or invite mails crashes script

### ISSUE THREAD

**Issue by acashley** [joeyates/imap-backup#40]
When backing up the Calendar folder or any individual Calendar invite/reply mails in the Inbox, the script crashes. The mailbox in question is an Office 365 mailbox.

Trace example from [Sent Items] folder as follows:

W, [2017-12-11T12:48:05.459451 #15793]  WARN -- : [Sent Items] failed to save message 40531:
Date: Fri, 07 Jul 2017 10:42:18 +0200
Subject: Accepted:Monthly Meeting
To: yyy.xxx@xyz.com
Content-Type: multipart/alternative; boundary="--_com.android.email_593210916315722"
MIME-Version: 1.0

----_com.android.email_593210916315722
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: base64

<snipped base 64>

----_com.android.email_593210916315722
Content-Type: text/calendar; method=REPLY;
 name="invite.ics"
Content-Transfer-Encoding: base64

<snipped base 64>

----_com.android.email_593210916315722--
. undefined method `[]' for nil:NilClass

**Comment by joeyates** [comment]
Thanks for the bug report - I'll look into it and get back to you.

**Comment by acashley** [comment]
Just following up on this one to see if there is any progress? Thanks!

**Comment by joeyates** [comment]
I've released an updated version: 1.2.2, with better logging on failures.
Could you see if that helps pinpoint the problem?

**Comment by acashley** [comment]
Pulled the updated code and re-ran the job. So far I haven't been able to reproduce this issue.
Not sure if it is successful now because the offending Calendar appointment no longer exists or something else has changed. Lets hope that is the end of it...

**Comment by joeyates** [comment]
I'll close for now.

Please reopen if you get the error again. Also, in that case, please post a sanitized log of the failure.
