### ISSUE TITLE
How do I run this as a cronjob ?

### ISSUE THREAD

**Issue by Tom-Jojo** [joeyates/imap-backup#41]
Hi,
This works great via SSH, but I cannot get I working via the Synology Task Scheduler (cron job). I get all sorts of errors.

Brgds/Tom

**Comment by joeyates** [comment]
Hi Tom,

Could you send me the errors you get?

Make sure you remove any sensitive info from the data.

Merry Christmas!

**Comment by Tom-Jojo** [comment]
Hi,

It generates the following error when run by the Synology task scheduler:
`Standard output/error:
/usr/lib/ruby/gems/2.4.0/gems/imap-backup-1.2.1/lib/imap/backup/configuration/store.rb:9:in `expand_path': couldn't find login name -- expanding `~' (ArgumentError)
	from /usr/lib/ruby/gems/2.4.0/gems/imap-backup-1.2.1/lib/imap/backup/configuration/store.rb:9:in `<class:Store>'
	from /usr/lib/ruby/gems/2.4.0/gems/imap-backup-1.2.1/lib/imap/backup/configuration/store.rb:8:in `<module:Backup>'
	from /usr/lib/ruby/gems/2.4.0/gems/imap-backup-1.2.1/lib/imap/backup/configuration/store.rb:5:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.4.0/gems/imap-backup-1.2.1/lib/imap/backup.rb:12:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.4.0/gems/imap-backup-1.2.1/bin/imap-backup:7:in `<top (required)>'
	from /bin/imap-backup:23:in `load'
	from /bin/imap-backup:23:in `<main>'
`
Brgds
Tom

**Comment by joeyates** [comment]
It looks like `HOME` environment variable is not set. Is there some way you can set that variable?

**Comment by Tom-Jojo** [comment]
Hi,
I have up at the time, but did not find another working solution.
I reinstalled Ruby and imap-backup today. It works fine now without any additional settings.

Thank you
/Tom
