### ISSUE TITLE
undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by a-krebs** [joeyates/imap-backup#46]
I have a message that cannot be saved. A minimal example that reproduces the error looks like the log output below:

```
W, [2018-03-18T22:10:59.768498 #12612]  WARN -- : [Folder/Subfolder] failed to save message 318:
Delivered-To: me@example.com
From: example <www.example.com>
To: FirstName LastName <me@example.com>
Subject: Re: no subject
. undefined method `+' for nil:NilClass
```

**Comment by a-krebs** [comment]
I have a unit test to demonstrate the issue and will open a pull request with a fix soon. Wanted to open the issue for completeness.

**Comment by joeyates** [comment]
Closing in favour of #46
