### ISSUE TITLE
chmod Problem

### ISSUE THREAD

**Issue by apographon** [joeyates/imap-backup#50]
Hi, I tried to run imap-backup on my synology. 
Everything worked fine - until I chwon'ed the backup directory.
}admin@Server:~/.imap-backup$ imap-backup
/usr/lib/ruby/2.4.0/fileutils.rb:1241:in `chmod': Operation not permitted @ chmod_internal - /volume2/web/imapbackup/oliver_statera.de (Errno::EPERM)
	from /usr/lib/ruby/2.4.0/fileutils.rb:1241:in `chmod'
	from /usr/lib/ruby/2.4.0/fileutils.rb:919:in `block in chmod'
	from /usr/lib/ruby/2.4.0/fileutils.rb:918:in `each'
	from /usr/lib/ruby/2.4.0/fileutils.rb:918:in `chmod'
	from /usr/lib/ruby/gems/2.4.0/gems/imap-backup-1.2.1/lib/imap/backup/utils.rb:30:in `block in make_folder'
	from /usr/lib/ruby/gems/2.4.0/gems/imap-backup-1.2.1/lib/imap/backup/utils.rb:28:in `each'
	from /usr/lib/ruby/gems/2.4.0/gems/imap-backup-1.2.1/lib/imap/backup/utils.rb:28:in `make_folder'
	from /usr/lib/ruby/gems/2.4.0/gems/imap-backup-1.2.1/lib/imap/backup/account/connection.rb:74:in `create_account_folder'
	from /usr/lib/ruby/gems/2.4.0/gems/imap-backup-1.2.1/lib/imap/backup/account/connection.rb:18:in `initialize'
	from /usr/lib/ruby/gems/2.4.0/gems/imap-backup-1.2.1/lib/imap/backup/configuration/list.rb:20:in `new'
	from /usr/lib/ruby/gems/2.4.0/gems/imap-backup-1.2.1/lib/imap/backup/configuration/list.rb:20:in `block in each_connection'
	from /usr/lib/ruby/gems/2.4.0/gems/imap-backup-1.2.1/lib/imap/backup/configuration/list.rb:19:in `each'
	from /usr/lib/ruby/gems/2.4.0/gems/imap-backup-1.2.1/lib/imap/backup/configuration/list.rb:19:in `each_connection'
	from /usr/lib/ruby/gems/2.4.0/gems/imap-backup-1.2.1/bin/imap-backup:66:in `<top (required)>'
	from /bin/imap-backup:23:in `load'
	from /bin/imap-backup:23:in `<main>'
admin@Server:~/.imap-backup$ 

And the config file is not used anymore.

I'm confused

**Comment by joeyates** [comment]
The permissions should be set as indicated here: https://github.com/joeyates/imap-backup#security . The directory containing the configuration should have permissions set to only allow acces to your user (0700).
