### ISSUE TITLE
Future feature (?): avoid storing password in clear text

### ISSUE THREAD

**Issue by johnnyutahh** [joeyates/imap-backup#55]
Is there any intent to provide a future feature to not store the IMAP account password in cleartext (currently in config.json file)?

(I did a quick search of existing issues and could not find similar issue, apologies if I missed something.)

**Comment by joeyates** [comment]
I think it would be great to not store the password in clear text, but finding and alternative is problematic...

As this is meant to be a standalone system, sooner or later it has to access the password. Where would it be stored and how would access to the store be unlocked?
