### ISSUE TITLE
mbox_store.rb:62:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by johnnyutahh** [joeyates/imap-backup#56]
gist of session output: https://goo.gl/X7iHCy

Also, I could probably wrangle with gem to fix the --version error, but I don't have the time resources right now.  --version was working just a couple mins ago, before it started failing (per the above gist):

```
   $ imap-backup --version
   2.0.0.rc1
   $

```

**Comment by joeyates** [comment]
If you're still getting this issue, please run with debugging enabled PM me an anonymized private Gist of the output.

**Comment by joeyates** [comment]
Closing. Please reopen if you're able to recover the Email that caused this crash.
