### ISSUE TITLE
email should be named username

### ISSUE THREAD

**Issue by MatejKovacic** [joeyates/imap-backup#63]
When running `imap-backup setup`, app asks you for your e-mail. However, it is not e-mail, it is actually username. For Gmail both are the same, but not for other servers.

And if you enter your username and try to test connection, app just crashes without printing out what the problem is.

Anyway, it would be nice to have option `imap-backup help` with description of all commands. Just an idea. :)

**Comment by joeyates** [comment]
@MatejKovacic good point about username, that'll need to be fixed (and kept backward-compatible).

PRs are always welcome ;-)
