### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by nihelmasell** [joeyates/imap-backup#66]
Hi, can you have many different gmail accounts backed up at the same time? If so, is this possible too with gmail plus non gmail accounts? Also, is the MBOX format searchable? (like with grep or any similar and straightforward utility) How can you perform frequent search/filterings into these files?Thanks in advance! Forgive my ignorance!

**Comment by joeyates** [comment]
Hi!

In terms of accounts any combination is fine.

MBOX is simply a text format, so, yes, you can grep it. If there are attachments things get a little more complicated, but the body of the message is fine. The good thing is that you can use existing mail clients to access MBOX file hierarchies, and that's probably the way to go.

**Comment by nihelmasell** [comment]
> Hi!
> 
> In terms of accounts any combination is fine.
> 
> MBOX is simply a text format, so, yes, you can grep it. If there are attachments things get a little more complicated, but the body of the message is fine. The good thing is that you can use existing mail clients to access MBOX file hierarchies, and that's probably the way to go.

I've read that mbox is the recommended format for long-term archiving. My problem is, how do you make reports, or perform a filtering of the data? Usually mail clients are slow when managing long databases (in my case 20 years of emails), and don't have advanced search options. In any case, I'm gonna give your app a try! It looks interesting!

**Comment by joeyates** [comment]
Glad to hear it!
