### ISSUE TITLE
Restore

### ISSUE THREAD

**Issue by joeyates** [joeyates/imap-backup#7]
Full restore:

```
$ imap-backup restore 
```

Single account:

```
$ imap-backup restore --accounts=me@example.com
```

Restore messages with a list of
- uids:
  
  $ imap-backup restore --accounts=me@example.com folder1 2345,2347 
- or ranges of uids:
  
  $ imap-backup restore --accounts=me@example.com folder1 123-456 
- or mixed:
  
  $ imap-backup restore --accounts=me@example.com folder1 2345,123-456

**Comment by rodrigoaguilera** [comment]
Is not very clear on the readme how to do a restore

**Comment by joeyates** [comment]
I'm afraid the implementation of the restore functionality (in a branch) is stalled at a pre-alpha phase.

**Comment by btxtiger** [comment]
What is the state of the branch?
I really need a tool to move a lot of email accounts to a new hosting provider.  
imap-backup worked well doing the backups.  I'm not really experienced with ruby, but if I get it running restoring the backups it will suffice my demands

**Comment by joeyates** [comment]
Restore is now merged in master.

**Comment by MatejKovacic** [comment]
I try to do `imap-backup restore`

And got this error:

```
Traceback (most recent call last):
	2: from /home/matej/gems/bin/imap-backup:23:in `<main>'
	1: from /home/matej/gems/bin/imap-backup:23:in `load'
/home/matej/gems/gems/imap-backup-1.4.2/bin/imap-backup:53:in `<top (required)>': Unknown command 'restore' (RuntimeError)
```

**Comment by joeyates** [comment]
@MatejKovacic restore is available in the 2.x release. Please note it is pre-release - i.e. tested loads by me, but I haven't had any community feedback.

**Comment by MatejKovacic** [comment]
I see... any instructions how to install 2.x branch?
