### ISSUE TITLE
Does imap-backup preserve dates when restoring?

### ISSUE THREAD

**Issue by deviantintegral** [joeyates/imap-backup#70]
My understanding is that many IMAP servers use the current date when uploading a new message. This breaks sorting on restored messages, as mail clients will use the current date and time for default sorts. For example, I have a restored message (from another tool) where the raw message is fine, but Fastmail shows as sent when the message was restore.

I'm curious if `imap-backup` has any workarounds for this? I'm not seeing anything obvious in the code, but I'm wondering if an upstream library handles it.

**Comment by joeyates** [comment]
Hello @deviantintegral 

Dates **are** set on restore. I've added a test for it. https://github.com/joeyates/imap-backup/commit/975db69796b6afd638ced05d2d7dc9e53aaac591
