### ISSUE TITLE
"Certificate verify failed"

### ISSUE THREAD

**Issue by nihelmasell** [joeyates/imap-backup#71]
Hi, I did what you told me. I edited the json file with my credentials, and I got the App password from Google. I get the following error "/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/imap.rb:1490:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)"

I don't know if its related to my environment (MacOs). I can try a linux virtual machine if you want (in which bistro are you testing the app?)

Best Regards

**Comment by joeyates** [comment]
Hello @nihelmasell 

The problem you're seeing relates to the CA certificates your Ruby is using. Maybe you could try this approach: https://www.engineyard.com/blog/ruby-ssl-error-certificate-verify-failed#solutions:

```sh
$ rvm osx-ssl-certs update all
```

**Comment by nihelmasell** [comment]
> Hello @nihelmasell
> 
> The problem you're seeing relates to the CA certificates your Ruby is using. Maybe you could try this approach: https://www.engineyard.com/blog/ruby-ssl-error-certificate-verify-failed#solutions:
> 
> ```shell
> $ rvm osx-ssl-certs update all
> ```

Thanks! It works
PS: It also worked your previous advise, using "ln -s /usr/local/opt/readline/lib/libreadline.8.0.dylib /usr/local/opt/readline/lib/libreadline.7.dylib" you can use the configuration wizard properly.

**Comment by joeyates** [comment]
Glad to hear it.
