### ISSUE TITLE
Problems when adding a Hotmail account

### ISSUE THREAD

**Issue by nihelmasell** [joeyates/imap-backup#72]
Hi, sorry to bother you again. I tested your program with gmail and worked really fine. The complete mailbox was downloaded and it was fully readable in Thunderbird. I tried afterwards to add a hotmail account, but got some issues. First, imap-backup hung without response. It stopped writing the mbox file and the program didn't respond. Then, I noticed the resulting box file was incomplete. Mails seems to be missing both from the day I opened the account and from the last two years. I am using imap-mail.outlook.com. I don't know if there's a suggested configuration for Microsoft's email.

**Comment by joeyates** [comment]
Thanks for the report, this needs checking. Please enable debug output and send me privately an anonimized output.
