### ISSUE TITLE
Windows - permissions issue with config file

### ISSUE THREAD

**Issue by nicholashead** [joeyates/imap-backup#78]
I know Windows doesn't seem to be officially supported, however I cannot get it to work with checking permissions on the config file. I can initially do the setup, save and exit - but running the app again complains that the permission on the config file isn't what it should be:

`Permissions on 'C:/Users/user/.imap-backup/config.json' should be 0600, not 0644.`

I have no idea what it's expecting to find or how to emulate 0600 chmod in Windows. I tried disabling inheritance on that `.imap-backup` folder and making only `user` have permissions to read/write, but it still fails the permissions check.

Any advice would be appreciated. If all else fails I'll maybe make my own fork that just disables the permissions check, or makes it a command line option.

**Comment by daniel-rikowski** [comment]
I don't think that is possible. On Windows Ruby only returns either `0644` or `0444` for files. (Source: https://ruby-doc.org/core-2.6.5/File.html, the last paragraphs)

I did some experiments using MSYS and WSL, too. MSYS detects 0644 for most files, while WSL shows 0777. When using chmod to change the permissions to 0600, both appear to succeed, but still show the original permissions. So even using these additional layers it seems to be hopeless.

I'm very interested in using imap-backup on Windows myself, so if you decide to create a fork, you might receive a few pull requests.

**Comment by nicholashead** [comment]
@daniel-rikowski good research. What I wound up doing locally is modifying one of the files to bypass the permissions check when loading from config, and it appears to be working 100% fine in native Windows (with the Windows ruby installer). I am not savvy with Ruby, but I can give it a go to see if I can make the check optional. But it's also good to know that imap-backup does indeed work under Windows.

**Comment by daniel-rikowski** [comment]
Agreed, skipping the permissions check seems to be the only thing necessary to make imap-backup work on Windows. 

I changed `lib/imap/backup/utils.rb` like this:

```ruby
def self.check_permissions(filename, limit)
  return if Gem.win_platform? # <---------
  actual = mode(filename)
  return nil if actual.nil?
  # Remaining code
end
```

**Comment by joeyates** [comment]
Thanks guys.

I'd really like to avoid removing the permissions check on a file with sensitive data in it.

Reading around, it looks like it's possible to set up ACLs for this type of thing. So, I'd prefer to keep this issue open for a while in the hope that someone comes up with a PR that maintains the current guarantees.

**Comment by nicholashead** [comment]
@joeyates right, I totally understand why it was done, it just seems like on Windows-based Ruby there's no current way to actually get back a response that would match what is being checked for in the codebase, if I read their docs correctly.

**Comment by joeyates** [comment]
@nicholashead @daniel-rikowski I've relased version 4.0.3 which no longer tries to do any permissions management on Windows. The permissions are simply inherited from the user's home directory, which by default is accessible by the user and admins.

**Comment by nicholashead** [comment]
@joeyates thank you! Can confirm it works great.
