### ISSUE TITLE
Incremental Backups

### ISSUE THREAD

**Issue by sstubbs** [joeyates/imap-backup#82]
Firstly I just wanted to say thank you for this amazing library. It's the first time imap backup/restore has been so simple and efficient. Does this do incremental backups or will it do a new backup each time?

**Comment by paulgessinger** [comment]
It only downloads messages that are not in t the local backup, so is effectively incremental. It doesn't save versions though u I believe. I'm running this in combination with Borg backup to make a snapshot after ever sync.

**Comment by joeyates** [comment]
@sstubbs Thanks for the question. As @paulgessinger says, imap-backup does a progressive backup. It has a list of message ids per folder and downloads the missing ones.

**Comment by sstubbs** [comment]
ok great thanks for the help.

**Comment by SpiritInAShell** [comment]
> @sstubbs Thanks for the question. As @paulgessinger says, imap-backup does a progressive backup. It has a list of message ids per folder and downloads the missing ones.

The IDs seem to be saved in a file `.IMAP` like `INBOX.IMAP`  and the mails stored in `INBOX.mbox`.

If I delete the `.mbox` file, the mails in this mailbox will be downloaded again (also `imap-backup status` displays a count>0 for `INBOX`)

If I zero out the `.mbox` file (eg. `echo > INBOX.mbox`), the mails will not be redownloaded (also `imap-backup status` displays a count=0 for `INBOX`).

Is this a coincidence, or a rule? can I reduce the size of my `imap-backup` local storage, eg. first using `borg backup` and then zero-ing out the `*.mbox` files?

**Comment by joeyates** [comment]
Hi @SpiritInAShell 

The choice of which emails need to be downloaded depends on the `.imap` files, so if they are zeroed out, everything will get downloaded again. On the other hand, if the `.mbox` file is modified, imap-backup will not download the emails again.

Modifying the `.imap` and `.mbox` files goes outside the scope of imap-backup, but if your use case is to reduce the size of the backup after copying the backup elsewhere, you **could** zero out the `.mbox` files, that may work. YMMV!
