### ISSUE TITLE
Restore performance

### ISSUE THREAD

**Issue by paulgessinger** [joeyates/imap-backup#83]
I'm trying to restore a large-ish account. I have about 30k messages in one folder (archive like GMail does). 

A few smaller folders in the same backup restored quickly, maybe a few seconds for about a hundred messages. 

The big folder though restores very slowly, and it seems to slow down the further in it gets. It started at a few messages per second and now it's at about 1.5min per message half way in. The message are small (kilobytes) and it doesn't seem to be limited by the network. 

Any idea why I'm seeing this? Could it be related to how the archive is traversed? To me this feels like it seeks to the current message from the top every time (but I don't actually know the code, so not sure).

**Comment by joeyates** [comment]
Hi @paulgessinger thanks for you question.

You are quite right, the current implementation does a linear scan on each upload. See here: https://github.com/joeyates/imap-backup/blob/162974a8dd07f906faa10336d07f06b2247a27e4/lib/imap/backup/serializer/mbox_store.rb#L145

It's a naive approach and is far from ideal. Ideally, the upload should step through the serialized emails with an enumerator. I am surprised, though, that it's getting so slow so quickly.

I'll open an enhancement issue to track this.
