### ISSUE TITLE
Linearly scan mboxes for message offsets before restores

### ISSUE THREAD

**Issue by joeyates** [joeyates/imap-backup#84]
As noted in #83, the current implementation is very inefficient. When restoring messages, it reparses the whole mbox from the beginning each time.

The method used is [load_nth](https://github.com/joeyates/imap-backup/blob/162974a8dd07f906faa10336d07f06b2247a27e4/lib/imap/backup/serializer/mbox_store.rb#L145).

The problem is that the implementation needs to be independent of the order of messages. The restore is of all missing messages, not just the last ones.

A better implementation would be to make a single pass over each folder, selecting out the messages that need to be restored.

As messages might be large enough to cause resource starvation, this first pass could collect start and end **offsets** of the messages in the mail box. The uploader would then just have to request chunks instead of causing a rescan.

**Comment by joeyates** [comment]
I've created the branch feature/optimize-restores that should resolve this issue.
I'm testing a bit more before releasing it. 

@paulgessinger Would you be able to test?

```sh
git clone https://github.com/joeyates/imap-backup.git
bundle
bin/imap-backup restore
```

**Comment by paulgessinger** [comment]
Thanks a lot!

I'll try to test it this weekend. I'll let you know what I find!

**Comment by paulgessinger** [comment]
So, preliminary, I can say that it looks to be faster. I want to do a more thorough comparison, but I haven't got around to it yet.

**Comment by paulgessinger** [comment]
![index](https://user-images.githubusercontent.com/1058585/94424325-51894f80-018a-11eb-8684-b779c27acd29.png)

Yeah it seems indeed to not only be faster, but also the trend is more or less flat, rather than going downwards as is the case for `2.2.1`. This was tested with a local IMAP server, so network etc. should not have any effect here. I can test with more volume if necessary, but this looks very good.

**Comment by joeyates** [comment]
Thanks @paulgessinger 

Nice graph!
Your tests confirm what I'm seeing myself. I'll cut a release.

**Comment by joeyates** [comment]
I've release version 2.2.2 with this change.
