### ISSUE TITLE
Question - Can this tool delete mail?

### ISSUE THREAD

**Issue by borpin** [joeyates/imap-backup#86]
In https://github.com/joeyates/imap-backup/issues/82#issuecomment-688633557 you say it doesn't delete mail.

I really don't want my archive to continually grow. Is it possible to add a feature where deleted email gets deleted?

**Comment by joeyates** [comment]
Hi @borpin 

If I understand correctly, I imagine that you want imap-backup to mirror the **current** status of your email account.

I know this might turn into a philosophical debate, but I think this libraries purpose is to do the opposite - to guarantee you have a copy of what gets deleted! :)

So, if I have understood your use case correctly, I would say it is outside the scope of this project.

On the other hand, you **can** use imap-backup as a mirror of the current status - just delete the backup before each run. Redownloading might be a problem if you have a lot of mail, but if your use case involves deleting mail on the server, I suspect this is not the case.

Thirdly, I'm open to pull requests for this feature, thought the PR would have to introduce a non-default switch.
