### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by alpham8** [joeyates/imap-backup#98]
Hi,

with this ``config.json`` I can't connect to the server, even if the firewall is completely disabled:
```
{
	"accounts": [
		{
			"username": "user.name@gmx.de",
			"password": "secret",
			"local_path": "/home/thomas/.imap-backup/user.name@gmx.de",
			"connection_options": {
				"port": 993
			}
		}
	]
}
```

The reply always in setup / testing is:
```
Unexpected error: Connection refused - connect(2) for 127.0.0.1:993
```

I'd be pleased for any help.

Thanks in advice,

alpham8

**Comment by m9aertner** [comment]
You need to set a "server" element in the config. Without that, `imap-backup` attempts to connect to your very own machine (127.0.0.1) which does not run an IMAP server on :993.

FWIW, I just checked that IONOS is working nice (same parent company as GMX), with config

    {
      "accounts": [
        {
          "username": "webmaster@xxxxxx.de",
          "password": "xxxxxxxxxxxxxxxxxx",
          "local_path": "/root/.imap-backup/webmaster_xxxxxx.de",
          "folders": [
    
          ],
          "server": "imap.1und1.de"
        }
      ],
      "debug": true
    }

**Comment by joeyates** [comment]
Hi @alpham8 

Does @m9aertner 's suggestion resolve the problem?

**Comment by alpham8** [comment]
Yes, thank you @joeyates and @m9aertner that solves my problem. Thankfully to that project, I'm now able to take mail backups :-)
