### ISSUE TITLE
Question: How to browse mails / content?

### ISSUE THREAD

**Issue by alpham8** [joeyates/imap-backup#99]
Hi all,

the backup and restore works fine. But however, I'm currently compeltely "blind" in what is included in the backup.

Is there a way to browse / view the backuped mails locally?

Second, would it be also possible to search for mails with a search engine like Elasticsearch?

Thanks in advice,

alpham8

**Comment by psy-q** [comment]
The backups are in mbox format so anything that can read mbox should be able to view them (e.g. mutt, [Mozilla Thunderbird](https://commons.lbl.gov/display/~jwelcher@lbl.gov/Reading+an+mbox+file+with+Thunderbird), Apple Mail, etc.). There are also separate mbox viewer tools, for example on Windows there is [https://sourceforge.net/projects/mbox-viewer/](mbox-viewer).

There is an [mbox indexer for Elasticsearch](https://github.com/oliver006/elasticsearch-gmail) you could customize. 

If your goal is to just quickly search through the messages on your client, you could also abuse Thunderbird for that. It will create a searchable index of all its folders automatically.

**Comment by alpham8** [comment]
@psy-q Thank you, I tried it with Thunderbird. But Thunderbird needs one folder for it. If I give it the whole Mailbox folder, then the half of the Mailbox is missing. May you please try it and tell me if it works for you?

You may find this site helpful. I did it like this: https://www.sysinfotools.com/blog/import-mbox-file-in-thunderbird/

**Comment by alpham8** [comment]
I just like to see what's included in the backup. Because currently I'm totally "blind"...

**Comment by psy-q** [comment]
Yes, that guide seems similar to the one I linked to earlier from Berkeley Labs. I don't typically use Thunderbird but it seems this trick still works, I just symlinked the .mbox directories imap-backup creates into the Local Folders directory as per the guide and they showed up in Thunderbird after I restarted. I could browse them fine, attachments and everything.

I didn't notice any missing messages, but in the case of subdirectories I did have to symlink directly to the .mbox files (not the subdirectories themselves). What messages are missing for you? If you look at the respective .mbox files in a text editor, do the messages you expect appear?

**Comment by alpham8** [comment]
@psy-q Nothing is missing, it's fine as I said in the beginning. I am able to restore everything. But I can't view anything locally in my backup folder using Thunderbird. Because I have run into the folder / subfolder problematic. May you explain your solution a bit in detail, please?

**Comment by psy-q** [comment]
Then I misunderstood what you meant by "If I give it the whole Mailbox folder, then the half of the Mailbox is missing". I thought you were seeing the content of some mbox files within the folder, but that not all the messages from each mbox file show up.

I hope in this case this stupid trick would work via symlinks:

`imap-backup/newsletters.mbox -> your_firefox_profile/Local Folders/newsletters.mbox`
`imap-backup/orders/2021.mbox -> your_firefox_profile/Local Folders/orders_2021.mbox`

So that a directory structure with subdirectories gets flattened into what looks like just one level of mbox files to Thunderbird. 

Maybe this little script can help flattening the pile of symlinks at the destination. It uses `___` in the folder names to act as a replacement for directory separators. Call it with `./link-imap-backup.rb [source] [destination]`, where source is the directory imap-backup stores its backups in and destination is your Firefox profile's `Local Folders`:

```ruby
#!/usr/bin/env ruby

source_dir = Dir.new(ARGV[0])
dest_dir = Dir.new(ARGV[1])
orig_dir = Dir.getwd

Dir.chdir(source_dir)

mbox_files = Dir.glob("**/*.mbox*")

mbox_files.each do |mf|
  source_path = File.join(source_dir, mf)
  dest_link = File.join(dest_dir, mf.split("/").join("___"))
  if File.exist?(dest_link)
    puts "Warning: Something at #{dest_link} already exists, skipping #{source_path}"
  else
    puts "Linking #{source_path} to #{dest_link}"
    File.symlink(source_path, dest_link)
  end
end

Dir.chdir(orig_dir)
```

**Comment by joeyates** [comment]
Hi @alpham8 

The next version of imap-backup will have functionality to list emails and view them (as raw - no functionality to view HTML emails or attachments!).
I've released this as version 4.0.0.rc1 if you want to have a look.

**Comment by joeyates** [comment]
@psy-q It would be nice to integrate an "Export to Thunderbird" functionality.

But, for imap-backup's restores to work, the '.imap' and '.mbox' files must remain aligned (one contains the ids and the other the messages).

So, I think it's problematic to give Thunderbird direct access to the mbox files as the user might alter them. So, it might be necessary to do this via copying and not symlinking.

**Comment by joeyates** [comment]
@psy-q @alpham8 The latest imap-backup (v4.0.2) includes an **experimental** export-to-thunderbird command.

**Comment by alpham8** [comment]
Thank you very much @joeyates @psy-q for that great support, love to hear that <3
